//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audit.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PropertiesNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertiesNames() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Audit.Core.Resources.PropertiesNames", typeof(PropertiesNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha y hora del acuerdo.
        /// </summary>
        internal static string AgreementDateHour {
            get {
                return ResourceManager.GetString("AgreementDateHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo del Acuerdo.
        /// </summary>
        internal static string AgreementFileId {
            get {
                return ResourceManager.GetString("AgreementFileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persona del Acuerdo.
        /// </summary>
        internal static string AgreementPersonId {
            get {
                return ResourceManager.GetString("AgreementPersonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación de cita.
        /// </summary>
        internal static string AppointmentId {
            get {
                return ResourceManager.GetString("AppointmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobado.
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de reclamo.
        /// </summary>
        internal static string ClaimNumber {
            get {
                return ResourceManager.GetString("ClaimNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Firma del Cliente.
        /// </summary>
        internal static string CustomerSignatureId {
            get {
                return ResourceManager.GetString("CustomerSignatureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Firma del Empleado.
        /// </summary>
        internal static string EmployeeSignatureId {
            get {
                return ResourceManager.GetString("EmployeeSignatureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguro.
        /// </summary>
        internal static string InsuranceCompanyId {
            get {
                return ResourceManager.GetString("InsuranceCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kilometraje.
        /// </summary>
        internal static string Mileage {
            get {
                return ResourceManager.GetString("Mileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio de próxima fecha.
        /// </summary>
        internal static string NextDateService {
            get {
                return ResourceManager.GetString("NextDateService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio de próximo kilometraje.
        /// </summary>
        internal static string NextMileageService {
            get {
                return ResourceManager.GetString("NextMileageService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de Cubo.
        /// </summary>
        internal static string NumberCube {
            get {
                return ResourceManager.GetString("NumberCube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones.
        /// </summary>
        internal static string Observations {
            get {
                return ResourceManager.GetString("Observations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color de Cubo.
        /// </summary>
        internal static string OrderColorCubeId {
            get {
                return ResourceManager.GetString("OrderColorCubeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orden Vinculada.
        /// </summary>
        internal static string OrderIdLinked {
            get {
                return ResourceManager.GetString("OrderIdLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de orden.
        /// </summary>
        internal static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orden Principal.
        /// </summary>
        internal static string OrderParentId {
            get {
                return ResourceManager.GetString("OrderParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Orden.
        /// </summary>
        internal static string OrderTypeId {
            get {
                return ResourceManager.GetString("OrderTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Área del Teléfono.
        /// </summary>
        internal static string PhoneAreaCode {
            get {
                return ResourceManager.GetString("PhoneAreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caracteristica del Pais.
        /// </summary>
        internal static string PhoneCountryId {
            get {
                return ResourceManager.GetString("PhoneCountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Teléfono.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bolsa de Producto.
        /// </summary>
        internal static string ProductBagId {
            get {
                return ResourceManager.GetString("ProductBagId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio próxima fecha tentativa.
        /// </summary>
        internal static string TentativeNextDateService {
            get {
                return ResourceManager.GetString("TentativeNextDateService", resourceCulture);
            }
        }
    }
}
